print('\nPlease enter the following: \n')

adjective_first = input('adjective: ')
animal_first = input('animal: ')
verb_first = input('verb: ')
exclamation = input('exclamation: ')
verb_second = input('verb: ')
verb_third = input('verb: ')
verb_fourth = input('past tense verb: ')
adjective_second = input('adjective: ')
animal_second = input('animal: ')
verb_fifth = input('verb: ')
food = input('food: ')
verb_sixth = input('verb: ')
noun_first = input('noun: ')
noun_second = input('noun: ')

print('\nYour story is: \n')
print('The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective_first} {animal_first} {verb_first} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb_second} over and over. Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb_third}')
print('right in front of my family.')
print(f'\nAfter that, it {verb_fourth} away. Then a different animal, a {adjective_second} {animal_second} {verb_fifth} down the')
print(f'street to the {food} {noun_first}. All I could do was wonder at what I had')
print(f'{verb_sixth}. Then a again, maybe it was all just a {noun_second}\n')